!!python/object/new:detectron2.config.config.CfgNode
dictitems:
  CUDNN_BENCHMARK: false
  DATALOADER: !!python/object/new:detectron2.config.config.CfgNode
    dictitems:
      ASPECT_RATIO_GROUPING: true
      FILTER_EMPTY_ANNOTATIONS: true
      NUM_WORKERS: 2
      REPEAT_SQRT: true
      REPEAT_THRESHOLD: 0.0
      SAMPLER_TRAIN: TrainingSampler
    state:
      __deprecated_keys__: !!set {}
      __immutable__: false
      __new_allowed__: false
      __renamed_keys__: {}
  DATASETS: !!python/object/new:detectron2.config.config.CfgNode
    dictitems:
      PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
      PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
      PROPOSAL_FILES_TEST: !!python/tuple []
      PROPOSAL_FILES_TRAIN: !!python/tuple []
      TEST: !!python/tuple []
      TRAIN: !!python/tuple
      - my_dataset_train
    state:
      __deprecated_keys__: !!set {}
      __immutable__: false
      __new_allowed__: false
      __renamed_keys__: {}
  GLOBAL: !!python/object/new:detectron2.config.config.CfgNode
    dictitems:
      HACK: 1.0
    state:
      __deprecated_keys__: !!set {}
      __immutable__: false
      __new_allowed__: false
      __renamed_keys__: {}
  INPUT: !!python/object/new:detectron2.config.config.CfgNode
    dictitems:
      CROP: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          ENABLED: false
          SIZE:
          - 0.9
          - 0.9
          TYPE: relative_range
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      FORMAT: BGR
      MASK_FORMAT: bitmask
      MAX_SIZE_TEST: 1333
      MAX_SIZE_TRAIN: 1333
      MIN_SIZE_TEST: 800
      MIN_SIZE_TRAIN: !!python/tuple
      - 640
      - 672
      - 704
      - 736
      - 768
      - 800
      MIN_SIZE_TRAIN_SAMPLING: choice
      RANDOM_FLIP: horizontal
    state:
      __deprecated_keys__: !!set {}
      __immutable__: false
      __new_allowed__: false
      __renamed_keys__: {}
  MODEL: !!python/object/new:detectron2.config.config.CfgNode
    dictitems:
      ANCHOR_GENERATOR: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          ANGLES:
          - - -90
            - 0
            - 90
          ASPECT_RATIOS:
          - - 0.5
            - 1.0
            - 2.0
          NAME: DefaultAnchorGenerator
          OFFSET: 0.0
          SIZES:
          - - 32
          - - 64
          - - 128
          - - 256
          - - 512
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      BACKBONE: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          FREEZE_AT: 2
          NAME: build_resnet_fpn_backbone
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      DEVICE: cuda
      FPN: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          FUSE_TYPE: sum
          IN_FEATURES:
          - res2
          - res3
          - res4
          - res5
          NORM: ''
          OUT_CHANNELS: 256
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      KEYPOINT_ON: false
      LOAD_PROPOSALS: false
      MASK_ON: true
      META_ARCHITECTURE: GeneralizedRCNN
      PANOPTIC_FPN: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          COMBINE: !!python/object/new:detectron2.config.config.CfgNode
            dictitems:
              ENABLED: true
              INSTANCES_CONFIDENCE_THRESH: 0.5
              OVERLAP_THRESH: 0.5
              STUFF_AREA_LIMIT: 4096
            state:
              __deprecated_keys__: !!set {}
              __immutable__: false
              __new_allowed__: false
              __renamed_keys__: {}
          INSTANCE_LOSS_WEIGHT: 1.0
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      PIXEL_MEAN:
      - 103.53
      - 116.28
      - 123.675
      PIXEL_STD:
      - 1.0
      - 1.0
      - 1.0
      PROPOSAL_GENERATOR: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          MIN_SIZE: 0
          NAME: RPN
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      RESNETS: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          DEFORM_MODULATED: false
          DEFORM_NUM_GROUPS: 1
          DEFORM_ON_PER_STAGE:
          - false
          - false
          - false
          - false
          DEPTH: 50
          NORM: FrozenBN
          NUM_GROUPS: 1
          OUT_FEATURES:
          - res2
          - res3
          - res4
          - res5
          RES2_OUT_CHANNELS: 256
          RES5_DILATION: 1
          STEM_OUT_CHANNELS: 64
          STRIDE_IN_1X1: true
          WIDTH_PER_GROUP: 64
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      RETINANET: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          BBOX_REG_LOSS_TYPE: smooth_l1
          BBOX_REG_WEIGHTS: &id002 !!python/tuple
          - 1.0
          - 1.0
          - 1.0
          - 1.0
          FOCAL_LOSS_ALPHA: 0.25
          FOCAL_LOSS_GAMMA: 2.0
          IN_FEATURES:
          - p3
          - p4
          - p5
          - p6
          - p7
          IOU_LABELS:
          - 0
          - -1
          - 1
          IOU_THRESHOLDS:
          - 0.4
          - 0.5
          NMS_THRESH_TEST: 0.5
          NORM: ''
          NUM_CLASSES: 80
          NUM_CONVS: 4
          PRIOR_PROB: 0.01
          SCORE_THRESH_TEST: 0.05
          SMOOTH_L1_LOSS_BETA: 0.1
          TOPK_CANDIDATES_TEST: 1000
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      ROI_BOX_CASCADE_HEAD: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          BBOX_REG_WEIGHTS: !!python/tuple
          - &id001 !!python/tuple
            - 10.0
            - 10.0
            - 5.0
            - 5.0
          - !!python/tuple
            - 20.0
            - 20.0
            - 10.0
            - 10.0
          - !!python/tuple
            - 30.0
            - 30.0
            - 15.0
            - 15.0
          IOUS: !!python/tuple
          - 0.5
          - 0.6
          - 0.7
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      ROI_BOX_HEAD: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          BBOX_REG_LOSS_TYPE: smooth_l1
          BBOX_REG_LOSS_WEIGHT: 1.0
          BBOX_REG_WEIGHTS: *id001
          CLS_AGNOSTIC_BBOX_REG: false
          CONV_DIM: 256
          FC_DIM: 1024
          FED_LOSS_FREQ_WEIGHT_POWER: 0.5
          FED_LOSS_NUM_CLASSES: 50
          NAME: FastRCNNConvFCHead
          NORM: ''
          NUM_CONV: 0
          NUM_FC: 2
          POOLER_RESOLUTION: 7
          POOLER_SAMPLING_RATIO: 0
          POOLER_TYPE: ROIAlignV2
          SMOOTH_L1_BETA: 0.0
          TRAIN_ON_PRED_BOXES: false
          USE_FED_LOSS: false
          USE_SIGMOID_CE: false
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      ROI_HEADS: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          BATCH_SIZE_PER_IMAGE: 64
          IN_FEATURES:
          - p2
          - p3
          - p4
          - p5
          IOU_LABELS:
          - 0
          - 1
          IOU_THRESHOLDS:
          - 0.5
          NAME: StandardROIHeads
          NMS_THRESH_TEST: 0.5
          NUM_CLASSES: 7
          POSITIVE_FRACTION: 0.25
          PROPOSAL_APPEND_GT: true
          SCORE_THRESH_TEST: 0.05
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      ROI_KEYPOINT_HEAD: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          CONV_DIMS: !!python/tuple
          - 512
          - 512
          - 512
          - 512
          - 512
          - 512
          - 512
          - 512
          LOSS_WEIGHT: 1.0
          MIN_KEYPOINTS_PER_IMAGE: 1
          NAME: KRCNNConvDeconvUpsampleHead
          NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
          NUM_KEYPOINTS: 17
          POOLER_RESOLUTION: 14
          POOLER_SAMPLING_RATIO: 0
          POOLER_TYPE: ROIAlignV2
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      ROI_MASK_HEAD: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          CLS_AGNOSTIC_MASK: false
          CONV_DIM: 256
          NAME: MaskRCNNConvUpsampleHead
          NORM: ''
          NUM_CONV: 4
          POOLER_RESOLUTION: 14
          POOLER_SAMPLING_RATIO: 0
          POOLER_TYPE: ROIAlignV2
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      RPN: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          BATCH_SIZE_PER_IMAGE: 256
          BBOX_REG_LOSS_TYPE: smooth_l1
          BBOX_REG_LOSS_WEIGHT: 1.0
          BBOX_REG_WEIGHTS: *id002
          BOUNDARY_THRESH: -1
          CONV_DIMS:
          - -1
          HEAD_NAME: StandardRPNHead
          IN_FEATURES:
          - p2
          - p3
          - p4
          - p5
          - p6
          IOU_LABELS:
          - 0
          - -1
          - 1
          IOU_THRESHOLDS:
          - 0.3
          - 0.7
          LOSS_WEIGHT: 1.0
          NMS_THRESH: 0.7
          POSITIVE_FRACTION: 0.5
          POST_NMS_TOPK_TEST: 1000
          POST_NMS_TOPK_TRAIN: 1000
          PRE_NMS_TOPK_TEST: 1000
          PRE_NMS_TOPK_TRAIN: 2000
          SMOOTH_L1_BETA: 0.0
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      SEM_SEG_HEAD: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          COMMON_STRIDE: 4
          CONVS_DIM: 128
          IGNORE_VALUE: 255
          IN_FEATURES:
          - p2
          - p3
          - p4
          - p5
          LOSS_WEIGHT: 1.0
          NAME: SemSegFPNHead
          NORM: GN
          NUM_CLASSES: 54
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      WEIGHTS: https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl
    state:
      __deprecated_keys__: !!set {}
      __immutable__: false
      __new_allowed__: false
      __renamed_keys__: {}
  OUTPUT_DIR: /content/drive/MyDrive/10DATA/Detectron2_Models
  SEED: -1
  SOLVER: !!python/object/new:detectron2.config.config.CfgNode
    dictitems:
      AMP: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          ENABLED: false
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      BASE_LR: 0.001
      BASE_LR_END: 0.0
      BIAS_LR_FACTOR: 1.0
      CHECKPOINT_PERIOD: 5000
      CLIP_GRADIENTS: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          CLIP_TYPE: value
          CLIP_VALUE: 1.0
          ENABLED: false
          NORM_TYPE: 2.0
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      GAMMA: 0.1
      IMS_PER_BATCH: 2
      LR_SCHEDULER_NAME: WarmupMultiStepLR
      MAX_ITER: 2000
      MOMENTUM: 0.9
      NESTEROV: false
      NUM_DECAYS: 3
      REFERENCE_WORLD_SIZE: 0
      RESCALE_INTERVAL: false
      STEPS: []
      WARMUP_FACTOR: 0.001
      WARMUP_ITERS: 1000
      WARMUP_METHOD: linear
      WEIGHT_DECAY: 0.0001
      WEIGHT_DECAY_BIAS: null
      WEIGHT_DECAY_NORM: 0.0
    state:
      __deprecated_keys__: !!set {}
      __immutable__: false
      __new_allowed__: false
      __renamed_keys__: {}
  TEST: !!python/object/new:detectron2.config.config.CfgNode
    dictitems:
      AUG: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          ENABLED: false
          FLIP: true
          MAX_SIZE: 4000
          MIN_SIZES: !!python/tuple
          - 400
          - 500
          - 600
          - 700
          - 800
          - 900
          - 1000
          - 1100
          - 1200
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
      DETECTIONS_PER_IMAGE: 100
      EVAL_PERIOD: 200
      EXPECTED_RESULTS: []
      KEYPOINT_OKS_SIGMAS: []
      PRECISE_BN: !!python/object/new:detectron2.config.config.CfgNode
        dictitems:
          ENABLED: false
          NUM_ITER: 200
        state:
          __deprecated_keys__: !!set {}
          __immutable__: false
          __new_allowed__: false
          __renamed_keys__: {}
    state:
      __deprecated_keys__: !!set {}
      __immutable__: false
      __new_allowed__: false
      __renamed_keys__: {}
  VERSION: 2
  VIS_PERIOD: 0
state:
  __deprecated_keys__: !!set {}
  __immutable__: false
  __new_allowed__: false
  __renamed_keys__: {}
